
# Import configuration
require 'yaml'

# Load config.yaml file
vagrantConfig = YAML.load_file('config.yaml')
machines = vagrantConfig['machines']
user = vagrantConfig['user']
sshKeyHostPath = vagrantConfig['sshKeyHostPath']
sshKeyBoxPath = vagrantConfig['sshKeyBoxPath']

Vagrant.configure("2") do |config|
  # loop machines
  machines.each do |type, typeConfig|

    # loop type of machines
    (1..typeConfig['number']).each do |i|

      machineName = "#{type}-#{i}"
      machineIp = "#{typeConfig['ip_base']}#{i + typeConfig['ip_start'] - 1}"

      # configure machine
      config.vm.define "#{machineName}" do |machine|

        machine.vm.box           = typeConfig['box']
        if typeConfig.has_key? 'box_version'
          machine.vm.box_version = typeConfig['box_version']
        end
        machine.vm.hostname      = "#{machineName}"
        machine.vm.network "public_network", ip: "#{machineIp}"
        machine.vm.provider "virtualbox" do |vb|
          vb.memory = "#{typeConfig['mem']}"
          vb.cpus   = "#{typeConfig['cpu']}"
          vb.name   = "#{machineName}"
          vb.gui    = true
        end
        config.vm.provision "file", source: sshKeyHostPath, destination: sshKeyBoxPath
        machine.vm.provision :shell, :path => "../scripts/setup.sh", :args => [user, sshKeyBoxPath]
      end
    end
  end
end
